site_name: gha-runner
nav:
  - Home: index.md
  - Implementations:
      - AWS: aws.md
  - API Reference:
      - Modules:
          - Cloud Deployment: api/clouddeployment.md
          - GitHub Interactions: api/gh.md
          - Helpers:
              - Workflow Commands: api/helper/workflow_cmds.md
              - Input: api/helper/input.md
theme: readthedocs
plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            filters:
              - "!^_"
            # Docstring style selection
            docstring_style: numpy # You can change this to 'numpy', 'sphinx', or 'restructuredtext'

            # Heading/Section Options
            show_root_heading: true
            show_root_full_path: false
            heading_level: 1

            # Members Options
            show_if_no_docstring: false
            show_source: true
            show_bases: true

            # Signature Options
            show_signature: true
            show_signature_annotations: true

            # Additional Options
            separate_signature: true
            line_length: 88
            inherited_members: false
