
name: Inference test
on:
  workflow_dispatch:

jobs:
  ec2:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      mapping: ${{ steps.aws-start.outputs.mapping }}
      instances: ${{ steps.aws-start.outputs.instances }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: us-east-1
      - name: Create cloud runner
        id: aws-start
        uses: Open-Athena/ec2-gha@rw/hooks
        with:
          ec2_image_id: ami-0f7c4a792e3fb63c8
          ec2_instance_type: g4dn.xlarge
          ec2_home_dir: /home/ubuntu
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
  inference-test:
    needs: ec2
    runs-on: ${{ needs.ec2.outputs.id }}
    defaults:
      run:
        shell: bash -leo pipefail {0}
    steps:
      - name: Checkout scripts
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            inference-test
          repository: omsf-eco-infra/ci-scripts
          path: ci-scripts
      - name: Print disk usage
        run: "df -h"
      - name: Print Docker details
        run: "docker version || true"
      - name: Check for nvidia-smi
        run: "nvidia-smi || true"
      - uses: mamba-org/setup-micromamba@main
        with:
          environment-file: ci-scripts/inference-test/environment.yml
      - name: Test for GPU
        id: gpu_test
        run: python ci-scripts/inference-test/inference.py
