name: Test OpenMM Test Installation
on:
  workflow_dispatch:

jobs:
  run-matrix:
    name: Run Matrix
    strategy:
      fail-fast: false
      matrix:
        instance_type: ["g4dn.xlarge", "t3.large"]
    uses: ./.github/workflows/reusable-gpu-test.yaml
    permissions:
      id-token: write
      contents: read
    with:
      instance_type: ${{ matrix.instance_type }}
    secrets: inherit # Bring in the secrets to the reused actions.
