name: Publish gha-runner
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install build
        run: >-
          python -m
          pip install
          build
          --user
      - name: Build binary wheel and source tarball
        run: python3 -m build
      - name: Store distribution
        uses: actions/upload-artifact@v4
        with:
          name: gha-runner-dists
          path: dist/
      - name: Determine release type
        id: release-type
        run: |
          if [[ "${{ github.event.release.prerelease }}" == "true" ]]; then
            echo "type=prerelease" >> "$GITHUB_OUTPUT"
          else
            echo "type=release" >> "$GITHUB_OUTPUT"
          fi

  publish-to-test-pypi:
    name: Publish distribution to test.pypi.org
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/gha_runner
    permissions:
      id-token: write
    if: needs.build.outputs.type == 'prerelease'
    steps:
      - name: Download the dists
        uses: actions/download-artifact@v4
        with:
          name: gha-runner-dists
          path: dist/
      - name: Publish to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true

  publish-to-pypi:
    name: Publish distribution to pypi.org
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/gha_runner
    permissions:
      id-token: write
    if: needs.build.outputs.type == 'release'
    steps:
      - name: Download the dists
        uses: actions/download-artifact@v4
        with:
          name: gha-runner-dists
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
